import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread('./amban.jpg', cv2.IMREAD_GRAYSCALE)
roberts_x = cv2.filter2D(img, cv2.CV_64F, np.array([[-1, 0], [0, 1]]))
roberts_y = cv2.filter2D(img, cv2.CV_64F, np.array([[0, -1], [1, 0]]))
roberts_magnitude = np.sqrt(roberts_x**2 + roberts_y**2)
sobel_x = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
sobel_y = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
sobel_magnitude = np.sqrt(sobel_x**2 + sobel_y**2)
prewitt_x = cv2.filter2D(img, cv2.CV_64F, np.array([[-1, 0, 1], [-1, 0, 1],[-1, 0, 1]]))
prewitt_y = cv2.filter2D(img, cv2.CV_64F, np.array([[-1, -1, -1], [0, 0, 0],[1, 1, 1]]))
prewitt_magnitude = np.sqrt(prewitt_x**2 + prewitt_y**2)
plt.figure(figsize=(12, 4))
plt.subplot(1, 4, 1)
plt.imshow(img, cmap='gray')
plt.title('Ảnh Gốc')
plt.axis('off')
plt.subplot(1, 4, 2)
plt.imshow(roberts_magnitude, cmap='gray')
plt.title('Robert')
plt.axis('off')
plt.subplot(1, 4, 3)
plt.imshow(sobel_magnitude, cmap='gray')
plt.title('Sobel')
plt.axis('off')
plt.subplot(1, 4, 4)
plt.imshow(prewitt_magnitude, cmap='gray')
plt.title('Prewitt')
plt.axis('off')
plt.show()