import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread('./amban.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.ones((5, 5), np.uint8)
erosion_img = cv2.erode(img, kernel, iterations=1)
dilation_img = cv2.dilate(img, kernel, iterations=1)
opening_img = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
closing_img = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)
plt.figure(figsize=(10, 8))
plt.subplot(2, 3, 1)
plt.imshow(img, cmap='gray')
plt.title('Ảnh Gốc')
plt.axis('off')
plt.subplot(2, 3, 2)
plt.imshow(erosion_img, cmap='gray')
plt.title('Phép Co')
plt.axis('off')
plt.subplot(2, 3, 3)
plt.imshow(dilation_img, cmap='gray')
plt.title('Phép Giãn')
plt.axis('off')
plt.subplot(2, 3, 4)
plt.imshow(opening_img, cmap='gray')
plt.title('Phép Mở Ảnh')
plt.axis('off')
plt.subplot(2, 3, 5)
plt.imshow(closing_img, cmap='gray')
plt.title('Phép Đóng Ảnh')
plt.axis('off')
plt.show()